### ISSUE TITLE
Topics Show Page

### ISSUE THREAD

**Issue by Dmo582251** [Dmo582251/forum_project2#1]
foo

**Comment by Dmo582251** [comment]
@awongh

**Comment by Dmo582251** [comment]
I am currently working on making the information of the post show up when you click on an individual user. My issue is an array comes up with nothing in it. 

Here is my code:(user.js)
//SHOW - specific users
    app.get('/users/:id', function (req, res){
        db.find("users", req.params.id, function (users){
            db.findRelations('posts', 'user_id', req.params.id, function (posts){
                console.log("THIS IS THE ISSUE:!!!", posts);
                var data = {
          users: users[0],
          posts: posts[0]
                };
                res.render('usersShow', data);
            }); 
        });
    });

userShow.handlebars:

  <h3>
    {{users.name}}
  </h3>

```
<img src="{{users.img_url}}" width="400" height="400">
```

  </a>

  <br>
  <div class="bio">
    <p>{{users.name}}
    <p>{{users.username}}</p>
    <p>{{users.bio}}</p>
    <p>{{users.date_made}}</p>
  </div>

  <br>

  <div class="post">
    <p>{{posts.description}}</p>
    <p>{{posts.location}}</p>
    <p>{{posts.date_made}}</p>
    <p>{{posts.like_count}}</p>
  </div>

**Comment by awongh** [comment]
Please use the _specific_ format in the "ask for help" doc- https://github.com/ga-students/WDI_skywalker/blob/master/project_one/asking_for_help.md

**Comment by awongh** [comment]
You can also tag the other instructors here

**Comment by awongh** [comment]
Also, you can link to your repo directly (by line number) using markdown (https://github.com/Dmo582251/forum_project2/blob/master/db.js#L8)
