### ISSUE TITLE
Attempting to have my user info come up in a topic

### ISSUE THREAD

**Issue by Dmo582251** [Dmo582251/forum_project2#3]
What User Story you are currently working on
- Displaying all posts in topic with user info
  What you are trying to do
  - access user info of the post when the topic is displayed

Detailed description of the bug or error
- I cannot access the user info
  Relevant code/files/errors, screenshots
  app.get('/topics/:id', function (req, res){
      db.find('topics', req.params.id, function (topic){
      // topics
      var data = {
          topic: topic[0]
      };
          db.findRelations('posts', 'topic_id', req.params.id, function (posts){
              data.topic.posts = posts;
              console.log("THESE ARE POSTS", posts);
  
  ```
          // data.topic.posts.forEach( function ( post, post_index, posts ){
          // });
  
          // for(var i = 0; i < posts.length; i++){
          //  db.find('users', posts[i-1].user_id , function (user){
          //      console.log("THIS IS THE USER SHIT", user);
          //      posts[i-1].user = user;
          //  });
          // };
  
          res.render('topicsShow', data);
  
          // var data = {
  ```
  
  //       topic: topic[0],
  //       posts: posts
              // };
              // console.log(req.session);
  
  ```
      }); 
  });
  ```
  
  });

PART 2:
Documentation you have looked at
- topics and posts
  Steps you have taken to solve the problem
- i have tried to do joins, loops, nest in a nest nothing is accessing the info
  Resources you have used
  websites

What would you like help with specifically?
- I would like help grabbibng the user info in the post and displaying it in the topic

@dbrodsky90 @WilliamfShaw

**Comment by WilliamfShaw** [comment]
Is a join, needs to be a joinnnnnnnn

**Comment by Dmo582251** [comment]
i think i tried multiple joins haha SO can we go over it really quickly at our meeting? <3

**Comment by WilliamfShaw** [comment]
Can you close this thing finally!!!!!!! I think we may have solved it a few months ago. Hope all is well!

**Comment by WilliamfShaw** [comment]
@Dmo582251 cmmmmmannnnnnnnnnnnnnn

**Comment by DBrodsky90** [comment]
@Dmo582251 cmmmmmannnnnnnnnnnnnnnnnnnnnnnn

**Comment by WilliamfShaw** [comment]
@Dmo582251 cmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmaaaaaaaaaaannnnnnnnnnnnnnnnnnnnnnnnnnn

**Comment by DBrodsky90** [comment]
@Dmo582251 Hey Dom, hope all is well. cmmmmmmannnnnnnnnnnnnnnnnnnnnn

**Comment by Dmo582251** [comment]
LOL I'm sorry! I haven't been on it!!!! Ill do it now
